In [1]:
import numpy as np 

In [2]:
np.array([2,3,4,6,7,8,9])

array([2, 3, 4, 6, 7, 8, 9])

In [5]:
a=[[2,4,5,6,7,8] , [3,7,0,9,2,5],[1,2,3,4,5,6]]

arr = np.array(a)
print(arr)

[[2 4 5 6 7 8]
 [3 7 0 9 2 5]
 [1 2 3 4 5 6]]


In [7]:
arr2=np.zeros((4,4))
arr2


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
a


[[2, 4, 5, 6, 7, 8], [3, 7, 0, 9, 2, 5], [1, 2, 3, 4, 5, 6]]

In [11]:
np.random.rand(10)

array([0.79680275, 0.78052969, 0.63036317, 0.26347404, 0.77742808,
       0.93992479, 0.14275554, 0.49540353, 0.36255181, 0.82634045])

In [13]:
np.random.randn(10)

array([ 0.19104109, -0.17893725, -0.73424138, -0.71023784, -0.56429948,
       -0.26323545, -0.33063022,  0.58874903,  2.74089196, -0.46968719])

In [15]:
np.random.randint(10,20,10)

array([19, 14, 17, 10, 12, 12, 12, 10, 17, 17], dtype=int32)

In [17]:
arr = np.array([[1,2,4],[3,6,7],[4,5,6,]])
arr


array([[1, 2, 4],
       [3, 6, 7],
       [4, 5, 6]])

In [20]:
arr.shape



(3, 3)

In [21]:
arr.min()

np.int64(1)

In [22]:
arr.max()   

np.int64(7)

In [23]:
arr.sum()

np.int64(38)

In [25]:
np.sum(arr,axis=1)


array([ 7, 16, 15])

In [26]:
arr.mean()

np.float64(4.222222222222222)

In [28]:
arr.std()

np.float64(1.8724777273725242)

In [29]:
  arr.argmax()

np.int64(5)

In [30]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [35]:
arr = arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])