In [1]:
import numpy as np


In [4]:
a1=np.array([1,2,3,4,5,6])
a2=np.ar ray([7,8,9,10,11,12])

In [9]:
a1 // a2

array([0, 0, 0, 0, 0, 0])

In [11]:
a1**a2

array([         1,        256,      19683,    1048576,   48828125,
       2176782336])

In [13]:
a1 +10+a2

array([18, 20, 22, 24, 26, 28])

In [15]:
arrr = np.arange(1,26).reshape(5,5)
arrr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])